# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Mon Sep 28 16:11:52 2020
# Model: Crop Pollination
# docker run --rm -it -v "%CD%":/usr/local/workspace therealspring/inspring:latest pollination_17guilds.py
# docker run --rm -it -v `pwd`:/usr/local/workspace therealspring/inspring:latest pollination_17guilds.py

import logging
import sys
import natcap.invest.pollination
from osgeo import gdal

gdal.SetCacheMax(2**28)

logging.basicConfig(
    level=logging.DEBUG,
    format=(
        '%(asctime)s (%(relativeCreated)d) %(levelname)s %(name)s'
        ' [%(funcName)s:%(lineno)d] %(message)s'),
    stream=sys.stdout)

LOGGER = logging.getLogger(__name__)
logging.getLogger('taskgraph').setLevel(logging.INFO)

args = {
    'farm_vector_path': 'coffee_iCAFE_2012_md5_da2a1cfcb05f4e2b6e0d878698593610.gpkg',
    'guild_table_path': 'guildtable_long_even_md5_b139c4a5457f0540bd1631ffe6b46133.csv',
    'landcover_biophysical_table_path': 'biophysical_costarica_md5_17ed6bbff3b7e3e6cfac7bb77345095f.csv',
    'landcover_raster_path': 'LULC_CR_clip_md5_63afaeac99fcb39a754ead3ab308031e.tif',
    'results_suffix': '17guilds',
    'workspace_dir': 'pollination_workspace',
}

if __name__ == '__main__':
    natcap.invest.pollination.execute(args)
